services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet10-api
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=mydb;Username=admin;Password=admin123"
    networks:
      - shared_net
    restart: unless-stopped
networks:
  shared_net:
    external: true